{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mcp-optimizer.fullname" . }}
  namespace: {{ .Values.mcpserver.namespace }}
  labels:
    {{- include "mcp-optimizer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      toolhive.stacklok.dev/mcpserver: {{ .Values.mcpserver.name }}
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

