version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - uv sync --dev --all-packages --group security --group examples

  lint:
    desc: Run linting with ruff
    cmds:
      - uv run ruff check .
    deps:
      - install

  format:
    desc: Fix linting issues and format code
    cmds:
      - uv run ruff format .
      - uv run ruff check --fix .
    deps:
      - install

  typecheck:
    desc: Run type checking with ty
    cmds:
      - uv run ty check .
    deps:
      - install

  test:
    desc: Run unit tests with pytest
    cmds:
      - uv run pytest
    deps:
      - install

  check:
    desc: Run all checks (lint, typecheck, tests, and security)
    deps:
      - lint
      - typecheck
      - test
      - security

  security:
    desc: Run security scanning
    cmds:
      - uv run bandit -r src/
      # TODO: Remove --ignore-vuln once protobuf releases a fix for CVE-2026-0994
      - uv run pip-audit --ignore-vuln CVE-2026-0994
      - uv run bandit -r src/ -f json -o bandit-report.json || true
      - uv run pip-audit --ignore-vuln CVE-2026-0994 --format=json --output=pip-audit-report.json || true
    deps:
      - install

  sbom:
    desc: Generate Software Bill of Materials (SBOM)
    cmds:
      - uv run cyclonedx-py environment --output-format json --output-file sbom.json
    deps:
      - install

  generate-thv-models:
    desc: Generate Pydantic models from Toolhive's OpenAPI specification
    cmds:
      - ./scripts/generate_toolhive_models.sh
    deps:
      - install

  run-migrations:
    desc: Run database migrations
    cmds:
      - uv run alembic upgrade head
    deps:
      - install

  download-models:
    desc: Download ML models for offline/airgapped deployments
    cmds:
      - uv sync --group offline-models
      - uv run python scripts/download_models.py

  build:
    desc: Build multi-architecture container image
    cmds:
      - docker buildx create --name mcp-optimizer-builder --use --bootstrap || docker buildx use mcp-optimizer-builder
      - docker buildx build --platform linux/amd64,linux/arm64 -t mcp-optimizer:latest --load .
    deps:
      - download-models

  build-local:
    desc: Build container image for local architecture only (faster for development)
    cmds:
      - docker build -t mcp-optimizer:latest .
    deps:
      - download-models

  run-container:
    desc: Run the application in a container (builds for local arch only)
    cmds:
      - task: build-local
      - docker rm -f mcp-optimizer-container || true
      - docker run --network host --name mcp-optimizer-container mcp-optimizer:latest

  install-hooks:
    desc: Install git hooks for the project
    cmds:
      - ./scripts/install-hooks.sh

  run-locally:
    desc: Run the application locally
    env:
      TOOLHIVE_HOST: "localhost"
      TOOLHIVE_PORT: "8080"
    cmds:
      - uv run mcpo
    deps:
      - install

  run-in-thv:
    desc: Build mcp-optimizer and run it in ToolHive
    cmds:
      - thv group create optim || true
      - thv rm mcp-optimizer || true
      - thv run mcp-optimizer:latest --transport streamable-http --group optim
    deps:
      - build-local

  offline-container-tests:
    desc: Run container offline mode tests
    cmds:
      - ./scripts/test-offline.sh

  k8s-apply-examples:
    desc: Apply all MCP server examples to Kubernetes cluster
    cmds:
      - ./examples/mcp-servers/apply-mcp-servers.sh

  k8s-delete-examples:
    desc: Delete all MCP server examples from Kubernetes cluster
    cmds:
      - ./examples/mcp-servers/delete-mcp-servers.sh

  k8s-status-examples:
    desc: Check status of all MCP server examples
    cmds:
      - ./examples/mcp-servers/status-mcp-servers.sh

  appworld-install:
    desc: Install AppWorld data (installs from source)
    cmds:
      - uv pip install pip
      - uv run pip install git+https://github.com/StacklokLabs/appworld.git
      - uv run appworld install
      - uv run appworld download data
      - uv run appworld --version

  appworld-serve-api:
    desc: Start AppWorld API server (port 9000) in isolated environment. Downloads base DBs if not present.
    cmds:
      - mkdir -p data/base_dbs
      - uv run appworld serve apis --port 9000

  appworld-serve-mcp:
    desc: Start AppWorld MCP server (port 10000) in isolated environment
    cmds:
      - uv run appworld serve mcp http --remote-apis-url http://localhost:9000 --port 10000

  appworld-experiment:
    desc: Run AppWorld experiment (requires servers running)
    cmds:
      - uv run python examples/call_tool_optimizer/run_experiment.py {{.CLI_ARGS}}

