# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-09T00:49:13+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Config(BaseModel):
    component: str | None = Field(
        None,
        description='Component is the component name to use in audit events.\n+optional',
    )
    enabled: bool | None = Field(
        None,
        description='Enabled controls whether audit logging is enabled.\nWhen true, enables audit logging with the configured options.\n+kubebuilder:default=false\n+optional',
    )
    event_types: list[str] | None = Field(
        None,
        alias='eventTypes',
        description='EventTypes specifies which event types to audit. If empty, all events are audited.\n+optional',
    )
    exclude_event_types: list[str] | None = Field(
        None,
        alias='excludeEventTypes',
        description='ExcludeEventTypes specifies which event types to exclude from auditing.\nThis takes precedence over EventTypes.\n+optional',
    )
    include_request_data: bool | None = Field(
        None,
        alias='includeRequestData',
        description='IncludeRequestData determines whether to include request data in audit logs.\n+kubebuilder:default=false\n+optional',
    )
    include_response_data: bool | None = Field(
        None,
        alias='includeResponseData',
        description='IncludeResponseData determines whether to include response data in audit logs.\n+kubebuilder:default=false\n+optional',
    )
    log_file: str | None = Field(
        None,
        alias='logFile',
        description='LogFile specifies the file path for audit logs. If empty, logs to stdout.\n+optional',
    )
    max_data_size: int | None = Field(
        None,
        alias='maxDataSize',
        description='MaxDataSize limits the size of request/response data included in audit logs (in bytes).\n+kubebuilder:default=1024\n+optional',
    )
