# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-04T00:43:07+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class SigningKeyRunConfig(BaseModel):
    fallback_key_files: list[str] | None = Field(
        None,
        description='FallbackKeyFiles are filenames of additional keys for verification (relative to KeyDir).\nThese keys are included in the JWKS endpoint for token verification but are NOT\nused for signing new tokens. Useful for key rotation.',
    )
    key_dir: str | None = Field(
        None,
        description='KeyDir is the directory containing PEM-encoded private key files.\nAll key filenames are relative to this directory.\nIn Kubernetes, this is typically a mounted Secret volume.',
    )
    signing_key_file: str | None = Field(
        None,
        description='SigningKeyFile is the filename of the primary signing key (relative to KeyDir).\nThis key is used for signing new tokens.',
    )


class TokenLifespanRunConfig(BaseModel):
    access_token_lifespan: str | None = Field(
        None,
        description='AccessTokenLifespan is the duration that access tokens are valid.\nIf empty, defaults to 1 hour.',
    )
    auth_code_lifespan: str | None = Field(
        None,
        description='AuthCodeLifespan is the duration that authorization codes are valid.\nIf empty, defaults to 10 minutes.',
    )
    refresh_token_lifespan: str | None = Field(
        None,
        description='RefreshTokenLifespan is the duration that refresh tokens are valid.\nIf empty, defaults to 7 days (168h).',
    )


class UpstreamProviderType(StrEnum):
    upstream_provider_type_oidc = 'oidc'
    upstream_provider_type_o_auth2 = 'oauth2'


class UserInfoFieldMappingRunConfig(BaseModel):
    email_fields: list[str] | None = Field(
        None,
        description='EmailFields is an ordered list of field names to try for the email address.\nThe first non-empty value found will be used.\nDefault: ["email"]',
    )
    name_fields: list[str] | None = Field(
        None,
        description='NameFields is an ordered list of field names to try for the display name.\nThe first non-empty value found will be used.\nDefault: ["name"]',
    )
    subject_fields: list[str] | None = Field(
        None,
        description='SubjectFields is an ordered list of field names to try for the user ID.\nThe first non-empty value found will be used.\nDefault: ["sub"]',
    )


class UserInfoRunConfig(BaseModel):
    additional_headers: dict[str, str] | None = Field(
        None,
        description="AdditionalHeaders contains extra headers to include in the userinfo request.\nUseful for providers that require specific headers (e.g., GitHub's Accept header).",
    )
    endpoint_url: str | None = Field(
        None, description='EndpointURL is the URL of the userinfo endpoint.'
    )
    field_mapping: UserInfoFieldMappingRunConfig | None = None
    http_method: str | None = Field(
        None,
        description='HTTPMethod is the HTTP method to use for the userinfo request.\nIf not specified, defaults to GET.',
    )


class OAuth2UpstreamRunConfig(BaseModel):
    authorization_endpoint: str | None = Field(
        None,
        description='AuthorizationEndpoint is the URL for the OAuth authorization endpoint.',
    )
    client_id: str | None = Field(
        None,
        description='ClientID is the OAuth 2.0 client identifier registered with the upstream IDP.',
    )
    client_secret_env_var: str | None = Field(
        None,
        description='ClientSecretEnvVar is the name of an environment variable containing the client secret.\nMutually exclusive with ClientSecretFile. Optional for public clients using PKCE.',
    )
    client_secret_file: str | None = Field(
        None,
        description='ClientSecretFile is the path to a file containing the OAuth 2.0 client secret.\nMutually exclusive with ClientSecretEnvVar. Optional for public clients using PKCE.',
    )
    redirect_uri: str | None = Field(
        None,
        description='RedirectURI is the callback URL where the upstream IDP will redirect after authentication.\nWhen not specified, defaults to `{issuer}/oauth/callback`.',
    )
    scopes: list[str] | None = Field(
        None,
        description='Scopes are the OAuth scopes to request from the upstream IDP.',
    )
    token_endpoint: str | None = Field(
        None, description='TokenEndpoint is the URL for the OAuth token endpoint.'
    )
    userinfo: UserInfoRunConfig | None = None


class OIDCUpstreamRunConfig(BaseModel):
    client_id: str | None = Field(
        None,
        description='ClientID is the OAuth 2.0 client identifier registered with the upstream IDP.',
    )
    client_secret_env_var: str | None = Field(
        None,
        description='ClientSecretEnvVar is the name of an environment variable containing the client secret.\nMutually exclusive with ClientSecretFile. Optional for public clients using PKCE.',
    )
    client_secret_file: str | None = Field(
        None,
        description='ClientSecretFile is the path to a file containing the OAuth 2.0 client secret.\nMutually exclusive with ClientSecretEnvVar. Optional for public clients using PKCE.',
    )
    issuer_url: str | None = Field(
        None,
        description='IssuerURL is the OIDC issuer URL for automatic endpoint discovery.\nMust be a valid HTTPS URL.',
    )
    redirect_uri: str | None = Field(
        None,
        description='RedirectURI is the callback URL where the upstream IDP will redirect after authentication.\nWhen not specified, defaults to `{issuer}/oauth/callback`.',
    )
    scopes: list[str] | None = Field(
        None,
        description='Scopes are the OAuth scopes to request from the upstream IDP.\nIf not specified, defaults to ["openid", "offline_access"].',
    )
    userinfo_override: UserInfoRunConfig | None = None


class UpstreamRunConfig(BaseModel):
    name: str | None = Field(
        None,
        description='Name uniquely identifies this upstream.\nUsed for routing decisions and session binding in multi-upstream scenarios.\nIf empty when only one upstream is configured, defaults to "default".',
    )
    oauth2_config: OAuth2UpstreamRunConfig | None = None
    oidc_config: OIDCUpstreamRunConfig | None = None
    type: UpstreamProviderType | None = None


class RunConfig(BaseModel):
    allowed_audiences: list[str] | None = Field(
        None,
        description='AllowedAudiences is the list of valid resource URIs that tokens can be issued for.\nPer RFC 8707, the "resource" parameter in authorization and token requests is\nvalidated against this list. Required for MCP compliance.',
    )
    hmac_secret_files: list[str] | None = Field(
        None,
        description='HMACSecretFiles contains file paths to HMAC secrets for signing authorization codes\nand refresh tokens (opaque tokens).\nFirst file is the current secret (must be at least 32 bytes), subsequent files\nare for rotation/verification of existing tokens.\nIf empty, an ephemeral secret will be auto-generated (development only).',
    )
    issuer: str | None = Field(
        None,
        description='Issuer is the issuer identifier for this authorization server.\nThis will be included in the "iss" claim of issued tokens.\nMust be a valid HTTPS URL (or HTTP for localhost) without query, fragment, or trailing slash.',
    )
    schema_version: str | None = Field(
        None, description='SchemaVersion is the version of the RunConfig schema.'
    )
    scopes_supported: list[str] | None = Field(
        None,
        description='ScopesSupported lists the OAuth 2.0 scope values advertised in discovery documents.\nIf empty, defaults to ["openid", "offline_access"].',
    )
    signing_key_config: SigningKeyRunConfig | None = None
    token_lifespans: TokenLifespanRunConfig | None = None
    upstreams: list[UpstreamRunConfig] | None = Field(
        None,
        description='Upstreams configures connections to upstream Identity Providers.\nAt least one upstream is required - the server delegates authentication to these providers.\nCurrently only a single upstream is supported.',
    )
