# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-15T00:36:13+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class CedarConfig(BaseModel):
    entities_json: str | None = Field(
        None, description='EntitiesJSON is the JSON string representing Cedar entities'
    )
    policies: list[str] | None = Field(
        None, description='Policies is a list of Cedar policy strings'
    )


class Config(BaseModel):
    cedar: CedarConfig | None = None
    type: str | None = Field(
        None, description='Type is the type of authorization configuration.'
    )
    version: str | None = Field(
        None, description='Version is the version of the configuration format.'
    )
