# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-15T00:36:13+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class TokenValidatorConfig(BaseModel):
    allow_private_ip: bool | None = Field(
        None,
        alias='allowPrivateIP',
        description='AllowPrivateIP allows JWKS/OIDC endpoints on private IP addresses',
    )
    audience: str | None = Field(
        None, description='Audience is the expected audience for the token'
    )
    auth_token_file: str | None = Field(
        None,
        alias='authTokenFile',
        description='AuthTokenFile is the path to file containing bearer token for authentication',
    )
    cacert_path: str | None = Field(
        None,
        alias='cacertPath',
        description='CACertPath is the path to the CA certificate bundle for HTTPS requests',
    )
    client_id: str | None = Field(
        None, alias='clientID', description='ClientID is the OIDC client ID'
    )
    client_secret: str | None = Field(
        None,
        alias='clientSecret',
        description='ClientSecret is the optional OIDC client secret for introspection',
    )
    insecure_allow_http: bool | None = Field(
        None,
        alias='insecureAllowHTTP',
        description='InsecureAllowHTTP allows HTTP (non-HTTPS) OIDC issuers for development/testing\nWARNING: This is insecure and should NEVER be used in production',
    )
    introspection_url: str | None = Field(
        None,
        alias='introspectionURL',
        description='IntrospectionURL is the optional introspection endpoint for validating tokens',
    )
    issuer: str | None = Field(
        None,
        description='Issuer is the OIDC issuer URL (e.g., https://accounts.google.com)',
    )
    jwksurl: str | None = Field(
        None, description='JWKSURL is the URL to fetch the JWKS from'
    )
    resource_url: str | None = Field(
        None,
        alias='resourceURL',
        description='ResourceURL is the explicit resource URL for OAuth discovery (RFC 9728)',
    )
    scopes: list[str] | None = Field(
        None,
        description='Scopes is the list of OAuth scopes to advertise in the well-known endpoint (RFC 9728)\nIf empty, defaults to ["openid"]',
    )
