# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2025-11-24T00:38:36+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class CedarConfig(BaseModel):
    entities_json: Optional[str] = Field(
        None, description='EntitiesJSON is the JSON string representing Cedar entities'
    )
    policies: Optional[list[str]] = Field(
        None, description='Policies is a list of Cedar policy strings'
    )


class Config(BaseModel):
    cedar: Optional[CedarConfig] = None
    type: Optional[str] = Field(
        None, description='Type is the type of authorization configuration.'
    )
    version: Optional[str] = Field(
        None, description='Version is the version of the configuration format.'
    )
