# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-27T00:41:21+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Config(BaseModel):
    type: str | None = Field(
        None,
        description='Type is the type of authorization configuration (e.g., "cedarv1").',
    )
    version: str | None = Field(
        None, description='Version is the version of the configuration format.'
    )
