# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-10T00:53:36+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class ClientApp(StrEnum):
    roo_code = 'roo-code'
    cline = 'cline'
    cursor = 'cursor'
    vs_code_insider = 'vscode-insider'
    vs_code = 'vscode'
    claude_code = 'claude-code'
    windsurf = 'windsurf'
    windsurf_jet_brains = 'windsurf-jetbrains'
    amp_cli = 'amp-cli'
    amp_vs_code = 'amp-vscode'
    amp_cursor = 'amp-cursor'
    amp_vs_code_insider = 'amp-vscode-insider'
    amp_windsurf = 'amp-windsurf'
    lm_studio = 'lm-studio'
    goose = 'goose'
    trae = 'trae'
    continue_ = 'continue'
    open_code = 'opencode'
    kiro = 'kiro'
    antigravity = 'antigravity'
    zed = 'zed'
    gemini_cli = 'gemini-cli'
    vs_code_server = 'vscode-server'
    mistral_vibe = 'mistral-vibe'
    codex = 'codex'


class ClientAppStatus(BaseModel):
    client_type: ClientApp | None = None
    installed: bool | None = Field(
        None,
        description='Installed indicates whether the client is installed on the system',
    )
    registered: bool | None = Field(
        None,
        description='Registered indicates whether the client is registered in the ToolHive configuration',
    )


class RegisteredClient(BaseModel):
    groups: list[str] | None = None
    name: ClientApp | None = None
