# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-10T00:38:13+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class MCPClientStatus(BaseModel):
    client_type: str | None = Field(
        None, description='ClientType is the type of MCP client'
    )
    installed: bool | None = Field(
        None,
        description='Installed indicates whether the client is installed on the system',
    )
    registered: bool | None = Field(
        None,
        description='Registered indicates whether the client is registered in the ToolHive configuration',
    )


class RegisteredClient(BaseModel):
    groups: list[str] | None = None
    name: str | None = None
