# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-17T00:37:10+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import runtime, types


class Workload(BaseModel):
    created_at: str | None = Field(
        None, description='CreatedAt is the timestamp when the workload was created.'
    )
    group: str | None = Field(
        None,
        description='Group is the name of the group this workload belongs to, if any.',
    )
    labels: dict[str, str] | None = Field(
        None,
        description='Labels are the container labels (excluding standard ToolHive labels)',
    )
    name: str | None = Field(
        None,
        description='Name is the name of the workload.\nIt is used as a unique identifier.',
    )
    package: str | None = Field(
        None,
        description='Package specifies the Workload Package used to create this Workload.',
    )
    port: int | None = Field(
        None,
        description='Port is the port on which the workload is exposed.\nThis is embedded in the URL.',
    )
    proxy_mode: str | None = Field(
        None,
        description='ProxyMode is the proxy mode that clients should use to connect.\nFor stdio transports, this will be the proxy mode (sse or streamable-http).\nFor direct transports (sse/streamable-http), this will be the same as TransportType.',
    )
    remote: bool | None = Field(
        None,
        description='Remote indicates whether this is a remote workload (true) or a container workload (false).',
    )
    status: runtime.WorkloadStatus | None = None
    status_context: str | None = Field(
        None,
        description="StatusContext provides additional context about the workload's status.\nThe exact meaning is determined by the status and the underlying runtime.",
    )
    tools: list[str] | None = Field(
        None, description='ToolsFilter is the filter on tools applied to the workload.'
    )
    transport_type: types.TransportType | None = None
    url: str | None = Field(
        None,
        description='URL is the URL of the workload exposed by the ToolHive proxy.',
    )
