# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-08T00:58:38+00:00

from __future__ import annotations

from pydantic import BaseModel


class Group(BaseModel):
    name: str | None = None
    registered_clients: list[str] | None = None
