# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2025-11-17T00:37:19+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Group(BaseModel):
    name: Optional[str] = None
    registered_clients: Optional[list[str]] = None
