# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2025-11-27T00:35:41+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Config(BaseModel):
    load_global: Optional[bool] = Field(
        None, alias='loadGlobal', description='Whether to load global ignore patterns'
    )
    print_overlays: Optional[bool] = Field(
        None,
        alias='printOverlays',
        description='Whether to print resolved overlay paths for debugging',
    )
