# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-08T00:58:38+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Config(BaseModel):
    load_global: bool | None = Field(
        None, alias='loadGlobal', description='Whether to load global ignore patterns'
    )
    print_overlays: bool | None = Field(
        None,
        alias='printOverlays',
        description='Whether to print resolved overlay paths for debugging',
    )
