# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-19T00:42:09+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from . import permissions as permissions_1


class EnvVar(BaseModel):
    default: str | None = Field(
        None,
        description='Default is the value to use if the environment variable is not explicitly provided\nOnly used for non-required variables',
    )
    description: str | None = Field(
        None,
        description="Description is a human-readable explanation of the variable's purpose",
    )
    name: str | None = Field(
        None, description='Name is the environment variable name (e.g., API_KEY)'
    )
    required: bool | None = Field(
        None,
        description='Required indicates whether this environment variable must be provided\nIf true and not provided via command line or secrets, the user will be prompted for a value',
    )
    secret: bool | None = Field(
        None,
        description='Secret indicates whether this environment variable contains sensitive information\nIf true, the value will be stored as a secret rather than as a plain environment variable',
    )


class Header(BaseModel):
    choices: list[str] | None = Field(
        None,
        description='Choices provides a list of valid values for the header (optional)',
    )
    default: str | None = Field(
        None,
        description='Default is the value to use if the header is not explicitly provided\nOnly used for non-required headers',
    )
    description: str | None = Field(
        None,
        description="Description is a human-readable explanation of the header's purpose",
    )
    name: str | None = Field(
        None, description='Name is the header name (e.g., X-API-Key, Authorization)'
    )
    required: bool | None = Field(
        None,
        description='Required indicates whether this header must be provided\nIf true and not provided via command line or secrets, the user will be prompted for a value',
    )
    secret: bool | None = Field(
        None,
        description='Secret indicates whether this header contains sensitive information\nIf true, the value will be stored as a secret rather than as plain text',
    )


class OAuthConfig(BaseModel):
    authorize_url: str | None = Field(
        None,
        description='AuthorizeURL is the OAuth authorization endpoint URL\nUsed for non-OIDC OAuth flows when issuer is not provided',
    )
    callback_port: int | None = Field(
        None,
        description='CallbackPort is the specific port to use for the OAuth callback server\nIf not specified, a random available port will be used',
    )
    client_id: str | None = Field(
        None, description='ClientID is the OAuth client ID for authentication'
    )
    issuer: str | None = Field(
        None,
        description='Issuer is the OAuth/OIDC issuer URL (e.g., https://accounts.google.com)\nUsed for OIDC discovery to find authorization and token endpoints',
    )
    oauth_params: dict[str, str] | None = Field(
        None,
        description='OAuthParams contains additional OAuth parameters to include in the authorization request\nThese are server-specific parameters like "prompt", "response_mode", etc.',
    )
    resource: str | None = Field(
        None, description='Resource is the OAuth 2.0 resource indicator (RFC 8707)'
    )
    scopes: list[str] | None = Field(
        None,
        description='Scopes are the OAuth scopes to request\nIf not specified, defaults to ["openid", "profile", "email"] for OIDC',
    )
    token_url: str | None = Field(
        None,
        description='TokenURL is the OAuth token endpoint URL\nUsed for non-OIDC OAuth flows when issuer is not provided',
    )
    use_pkce: bool | None = Field(
        None,
        description='UsePKCE indicates whether to use PKCE for the OAuth flow\nDefaults to true for enhanced security',
    )


class RemoteServerMetadata(BaseModel):
    env_vars: list[EnvVar] | None = Field(
        None,
        description='EnvVars defines environment variables that can be passed to configure the client\nThese might be needed for client-side configuration when connecting to the remote server',
    )
    headers: list[Header] | None = Field(
        None,
        description="Headers defines HTTP headers that can be passed to the remote server for authentication\nThese are used with the thv proxy command's authentication features",
    )
    oauth_config: OAuthConfig | None = None
    url: str | None = Field(
        None,
        description='URL is the endpoint URL for the remote MCP server (e.g., https://api.example.com/mcp)',
    )


class VerifiedAttestation(BaseModel):
    predicate: Any | None = None
    predicate_type: str | None = None


class Provenance(BaseModel):
    attestation: VerifiedAttestation | None = None
    cert_issuer: str | None = None
    repository_ref: str | None = None
    repository_uri: str | None = None
    runner_environment: str | None = None
    signer_identity: str | None = None
    sigstore_url: str | None = None


class ImageMetadata(BaseModel):
    args: list[str] | None = Field(
        None,
        description='Args are the default command-line arguments to pass to the MCP server container.\nThese arguments will be used only if no command-line arguments are provided by the user.\nIf the user provides arguments, they will override these defaults.',
    )
    docker_tags: list[str] | None = Field(
        None,
        description='DockerTags lists the available Docker tags for this server image',
    )
    env_vars: list[EnvVar] | None = Field(
        None,
        description='EnvVars defines environment variables that can be passed to the server',
    )
    image: str | None = Field(
        None, description='Image is the Docker image reference for the MCP server'
    )
    permissions: permissions_1.Profile | None = None
    provenance: Provenance | None = None
    target_port: int | None = Field(
        None,
        description='TargetPort is the port for the container to expose (only applicable to SSE and Streamable HTTP transports)',
    )


class Group(BaseModel):
    description: str | None = Field(
        None,
        description="Description is a human-readable description of the group's purpose and functionality",
    )
    name: str | None = Field(
        None,
        description='Name is the identifier for the group, used when referencing the group in commands',
    )
    remote_servers: dict[str, RemoteServerMetadata] | None = Field(
        None,
        description='RemoteServers is a map of server names to their corresponding remote server definitions within this group',
    )
    servers: dict[str, ImageMetadata] | None = Field(
        None,
        description='Servers is a map of server names to their corresponding server definitions within this group',
    )


class Registry(BaseModel):
    groups: list[Group] | None = Field(
        None,
        description='Groups is a slice of group definitions containing related MCP servers',
    )
    last_updated: str | None = Field(
        None,
        description='LastUpdated is the timestamp when the registry was last updated, in RFC3339 format',
    )
    remote_servers: dict[str, RemoteServerMetadata] | None = Field(
        None,
        description='RemoteServers is a map of server names to their corresponding remote server definitions\nThese are MCP servers accessed via HTTP/HTTPS using the thv proxy command',
    )
    servers: dict[str, ImageMetadata] | None = Field(
        None,
        description='Servers is a map of server names to their corresponding server definitions',
    )
    version: str | None = Field(
        None, description='Version is the schema version of the registry'
    )
