# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2025-12-02T00:36:43+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from . import registry


class Config(BaseModel):
    authorize_url: Optional[str] = None
    callback_port: Optional[int] = None
    client_id: Optional[str] = None
    client_secret: Optional[str] = None
    client_secret_file: Optional[str] = None
    env_vars: Optional[list[registry.EnvVar]] = Field(
        None, description='Environment variables for the client'
    )
    headers: Optional[list[registry.Header]] = Field(
        None, description='Headers for HTTP requests'
    )
    issuer: Optional[str] = Field(
        None, description='OAuth endpoint configuration (from registry)'
    )
    oauth_params: Optional[dict[str, str]] = Field(
        None, description='OAuth parameters for server-specific customization'
    )
    resource: Optional[str] = Field(
        None, description='Resource is the OAuth 2.0 resource indicator (RFC 8707).'
    )
    scopes: Optional[list[str]] = None
    skip_browser: Optional[bool] = None
    timeout: Optional[str] = Field(None, examples=['5m'])
    token_url: Optional[str] = None
    use_pkce: Optional[bool] = None
