# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-06T00:44:21+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import registry


class Config(BaseModel):
    authorize_url: str | None = None
    bearer_token: str | None = Field(
        None, description='Bearer token configuration (alternative to OAuth)'
    )
    bearer_token_file: str | None = None
    cached_client_id: str | None = Field(
        None,
        description="Cached DCR client credentials for persistence across restarts.\nThese are obtained during Dynamic Client Registration and needed to refresh tokens.\nClientID is stored as plain text since it's public information.",
    )
    cached_client_secret_ref: str | None = None
    cached_refresh_token_ref: str | None = Field(
        None,
        description='Cached OAuth token reference for persistence across restarts.\nThe refresh token is stored securely in the secret manager, and this field\ncontains the reference to retrieve it (e.g., "OAUTH_REFRESH_TOKEN_workload").\nThis enables session restoration without requiring a new browser-based login.',
    )
    cached_reg_token_ref: str | None = Field(
        None,
        description="RegistrationAccessToken is used to update/delete the client registration.\nStored as a secret reference since it's sensitive.",
    )
    cached_secret_expiry: str | None = Field(
        None,
        description='ClientSecretExpiresAt indicates when the client secret expires (if provided by the DCR server).\nA zero value means the secret does not expire.',
    )
    cached_token_expiry: str | None = None
    callback_port: int | None = None
    client_id: str | None = None
    client_secret: str | None = None
    client_secret_file: str | None = None
    env_vars: list[registry.EnvVar] | None = Field(
        None, description='Environment variables for the client'
    )
    headers: list[registry.Header] | None = Field(
        None, description='Headers for HTTP requests'
    )
    issuer: str | None = Field(
        None, description='OAuth endpoint configuration (from registry)'
    )
    oauth_params: dict[str, str] | None = Field(
        None, description='OAuth parameters for server-specific customization'
    )
    resource: str | None = Field(
        None, description='Resource is the OAuth 2.0 resource indicator (RFC 8707).'
    )
    scopes: list[str] | None = None
    skip_browser: bool | None = None
    timeout: str | None = Field(None, examples=['5m'])
    token_url: str | None = None
    use_pkce: bool | None = None
