# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-13T00:34:49+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import (
    audit,
    auth,
    authz,
    ignore,
    permissions,
    remote,
    telemetry,
    tokenexchange,
    types,
)


class ToolOverride(BaseModel):
    description: str | None = Field(
        None, description='Description is the redefined description of the tool'
    )
    name: str | None = Field(None, description='Name is the redefined name of the tool')


class RunConfig(BaseModel):
    audit_config: audit.Config | None = None
    audit_config_path: str | None = Field(
        None, description='AuditConfigPath is the path to the audit configuration file'
    )
    authz_config: authz.Config | None = None
    authz_config_path: str | None = Field(
        None,
        description='AuthzConfigPath is the path to the authorization configuration file',
    )
    base_name: str | None = Field(
        None,
        description='BaseName is the base name used for the container (without prefixes)',
    )
    cmd_args: list[str] | None = Field(
        None, description='CmdArgs are the arguments to pass to the container'
    )
    container_labels: dict[str, str] | None = Field(
        None, description='ContainerLabels are the labels to apply to the container'
    )
    container_name: str | None = Field(
        None, description='ContainerName is the name of the container'
    )
    debug: bool | None = Field(
        None, description='Debug indicates whether debug mode is enabled'
    )
    endpoint_prefix: str | None = Field(
        None,
        description='EndpointPrefix is an explicit prefix to prepend to SSE endpoint URLs.\nThis is used to handle path-based ingress routing scenarios.',
    )
    env_file_dir: str | None = Field(
        None,
        description='EnvFileDir is the directory path to load environment files from',
    )
    env_vars: dict[str, str] | None = Field(
        None,
        description='EnvVars are the parsed environment variables as key-value pairs',
    )
    group: str | None = Field(
        None,
        description='Group is the name of the group this workload belongs to, if any',
    )
    host: str | None = Field(None, description='Host is the host for the HTTP proxy')
    ignore_config: ignore.Config | None = None
    image: str | None = Field(None, description='Image is the Docker image to run')
    isolate_network: bool | None = Field(
        None,
        description='IsolateNetwork indicates whether to isolate the network for the container',
    )
    jwks_auth_token_file: str | None = Field(
        None,
        description='JWKSAuthTokenFile is the path to file containing auth token for JWKS/OIDC requests',
    )
    k8s_pod_template_patch: str | None = Field(
        None,
        description='K8sPodTemplatePatch is a JSON string to patch the Kubernetes pod template\nOnly applicable when using Kubernetes runtime',
    )
    middleware_configs: list[types.MiddlewareConfig] | None = Field(
        None,
        description='MiddlewareConfigs contains the list of middleware to apply to the transport\nand the configuration for each middleware.',
    )
    name: str | None = Field(None, description='Name is the name of the MCP server')
    oidc_config: auth.TokenValidatorConfig | None = None
    permission_profile: permissions.Profile | None = None
    permission_profile_name_or_path: str | None = Field(
        None,
        description='PermissionProfileNameOrPath is the name or path of the permission profile',
    )
    port: int | None = Field(
        None, description='Port is the port for the HTTP proxy to listen on (host port)'
    )
    proxy_mode: str | None = Field(
        None,
        description='ProxyMode is the proxy mode for stdio transport ("sse" or "streamable-http")\nNote: "sse" is deprecated; use "streamable-http" instead.',
    )
    remote_auth_config: remote.Config | None = None
    remote_url: str | None = Field(
        None,
        description='RemoteURL is the URL of the remote MCP server (if running remotely)',
    )
    schema_version: str | None = Field(
        None, description='SchemaVersion is the version of the RunConfig schema'
    )
    secrets: list[str] | None = Field(
        None,
        description='Secrets are the secret parameters to pass to the container\nFormat: "<secret name>,target=<target environment variable>"',
    )
    target_host: str | None = Field(
        None,
        description='TargetHost is the host to forward traffic to (only applicable to SSE transport)',
    )
    target_port: int | None = Field(
        None,
        description='TargetPort is the port for the container to expose (only applicable to SSE transport)',
    )
    telemetry_config: telemetry.Config | None = None
    thv_ca_bundle: str | None = Field(
        None,
        description='ThvCABundle is the path to the CA certificate bundle for ToolHive HTTP operations',
    )
    token_exchange_config: tokenexchange.Config | None = None
    tools_filter: list[str] | None = Field(
        None, description='ToolsFilter is the list of tools to filter'
    )
    tools_override: dict[str, ToolOverride] | None = Field(
        None,
        description='ToolsOverride is a map from an actual tool to its overridden name and/or description',
    )
    transport: str | None = Field(
        None,
        description='Transport is the transport mode (stdio, sse, or streamable-http)',
    )
    trust_proxy_headers: bool | None = Field(
        None,
        description='TrustProxyHeaders indicates whether to trust X-Forwarded-* headers from reverse proxies',
    )
    volumes: list[str] | None = Field(
        None,
        description='Volumes are the directory mounts to pass to the container\nFormat: "host-path:container-path[:ro]"',
    )
