# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-06T00:44:21+00:00

from __future__ import annotations

from enum import StrEnum


class WorkloadStatus(StrEnum):
    workload_status_running = 'running'
    workload_status_stopped = 'stopped'
    workload_status_error = 'error'
    workload_status_starting = 'starting'
    workload_status_stopping = 'stopping'
    workload_status_unhealthy = 'unhealthy'
    workload_status_removing = 'removing'
    workload_status_unknown = 'unknown'
    workload_status_unauthenticated = 'unauthenticated'
