# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-10T00:53:36+00:00

from __future__ import annotations

from pydantic import BaseModel


class SecretParameter(BaseModel):
    name: str | None = None
    target: str | None = None
