# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-09T00:49:13+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class BuildResult(BaseModel):
    reference: str | None = Field(
        None, description='Reference is the OCI reference of the built skill artifact.'
    )


class InstallStatus(StrEnum):
    install_status_installed = 'installed'
    install_status_pending = 'pending'
    install_status_failed = 'failed'


class Scope(StrEnum):
    scope_user = 'user'
    scope_system = 'system'


class SkillMetadata(BaseModel):
    author: str | None = Field(
        None, description='Author is the skill author or maintainer.'
    )
    description: str | None = Field(
        None, description='Description is a human-readable description of the skill.'
    )
    name: str | None = Field(None, description='Name is the unique name of the skill.')
    tags: list[str] | None = Field(
        None, description='Tags is a list of tags for categorization.'
    )
    version: str | None = Field(
        None, description='Version is the semantic version of the skill.'
    )


class ValidationResult(BaseModel):
    errors: list[str] | None = Field(
        None, description='Errors is a list of validation errors, if any.'
    )
    valid: bool | None = Field(
        None, description='Valid indicates whether the skill definition is valid.'
    )


class InstalledSkill(BaseModel):
    clients: list[str] | None = Field(
        None,
        description='Clients is the list of client identifiers the skill is installed for.\nTODO: Refactor client.MCPClient to a shared package so it can be used here instead of []string.',
    )
    installed_at: str | None = Field(
        None, description='InstalledAt is the timestamp when the skill was installed.'
    )
    metadata: SkillMetadata | None = None
    scope: Scope | None = None
    status: InstallStatus | None = None


class SkillInfo(BaseModel):
    installed: bool | None = Field(
        None,
        description='Installed indicates whether the skill is currently installed.',
    )
    installed_skill: InstalledSkill | None = None
    metadata: SkillMetadata | None = None
