# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-01T00:54:09+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Config(BaseModel):
    custom_attributes: dict[str, str] | None = Field(
        None,
        alias='customAttributes',
        description='CustomAttributes contains custom resource attributes to be added to all telemetry signals.\nThese are parsed from CLI flags (--otel-custom-attributes) or environment variables\n(OTEL_RESOURCE_ATTRIBUTES) as key=value pairs.\n+optional',
    )
    enable_prometheus_metrics_path: bool | None = Field(
        None,
        alias='enablePrometheusMetricsPath',
        description='EnablePrometheusMetricsPath controls whether to expose Prometheus-style /metrics endpoint.\nThe metrics are served on the main transport port at /metrics.\nThis is separate from OTLP metrics which are sent to the Endpoint.\n+kubebuilder:default=false\n+optional',
    )
    endpoint: str | None = Field(
        None, description='Endpoint is the OTLP endpoint URL\n+optional'
    )
    environment_variables: list[str] | None = Field(
        None,
        alias='environmentVariables',
        description='EnvironmentVariables is a list of environment variable names that should be\nincluded in telemetry spans as attributes. Only variables in this list will\nbe read from the host machine and included in spans for observability.\nExample: ["NODE_ENV", "DEPLOYMENT_ENV", "SERVICE_VERSION"]\n+optional',
    )
    headers: dict[str, str] | None = Field(
        None,
        description='Headers contains authentication headers for the OTLP endpoint.\n+optional',
    )
    insecure: bool | None = Field(
        None,
        description='Insecure indicates whether to use HTTP instead of HTTPS for the OTLP endpoint.\n+kubebuilder:default=false\n+optional',
    )
    metrics_enabled: bool | None = Field(
        None,
        alias='metricsEnabled',
        description='MetricsEnabled controls whether OTLP metrics are enabled.\nWhen false, OTLP metrics are not sent even if an endpoint is configured.\nThis is independent of EnablePrometheusMetricsPath.\n+kubebuilder:default=false\n+optional',
    )
    sampling_rate: str | None = Field(
        None,
        alias='samplingRate',
        description='SamplingRate is the trace sampling rate (0.0-1.0) as a string.\nOnly used when TracingEnabled is true.\nExample: "0.05" for 5% sampling.\n+kubebuilder:default="0.05"\n+optional',
    )
    service_name: str | None = Field(
        None,
        alias='serviceName',
        description='ServiceName is the service name for telemetry.\nWhen omitted, defaults to the server name (e.g., VirtualMCPServer name).\n+optional',
    )
    service_version: str | None = Field(
        None,
        alias='serviceVersion',
        description='ServiceVersion is the service version for telemetry.\nWhen omitted, defaults to the ToolHive version.\n+optional',
    )
    tracing_enabled: bool | None = Field(
        None,
        alias='tracingEnabled',
        description='TracingEnabled controls whether distributed tracing is enabled.\nWhen false, no tracer provider is created even if an endpoint is configured.\n+kubebuilder:default=false\n+optional',
    )
