# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-10T00:53:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class RuntimeConfig(BaseModel):
    additional_packages: list[str] | None = Field(
        None,
        description='AdditionalPackages lists extra packages to install in builder stage\nExamples for Alpine: ["git", "make", "gcc"]\nExamples for Debian: ["git", "build-essential"]',
    )
    builder_image: str | None = Field(
        None,
        description='BuilderImage is the full image reference for the builder stage\nExamples: "golang:1.25-alpine", "node:22-alpine", "python:3.13-slim"',
    )
