# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2025-11-20T00:35:20+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Config(BaseModel):
    audience: Optional[str] = Field(
        None, description='Audience is the target audience for the exchanged token'
    )
    client_id: Optional[str] = Field(
        None, description='ClientID is the OAuth 2.0 client identifier'
    )
    client_secret: Optional[str] = Field(
        None, description='ClientSecret is the OAuth 2.0 client secret'
    )
    external_token_header_name: Optional[str] = Field(
        None,
        description='ExternalTokenHeaderName is the name of the custom header to use when HeaderStrategy is "custom"',
    )
    header_strategy: Optional[str] = Field(
        None,
        description='HeaderStrategy determines how to inject the token\nValid values: HeaderStrategyReplace (default), HeaderStrategyCustom',
    )
    scopes: Optional[list[str]] = Field(
        None,
        description='Scopes is the list of scopes to request for the exchanged token',
    )
    subject_token_type: Optional[str] = Field(
        None,
        description='SubjectTokenType specifies the type of the subject token being exchanged.\nCommon values: tokenTypeAccessToken (default), tokenTypeIDToken, tokenTypeJWT.\nIf empty, defaults to tokenTypeAccessToken.',
    )
    token_url: Optional[str] = Field(
        None, description='TokenURL is the OAuth 2.0 token endpoint URL'
    )
