# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-20T00:38:17+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Config(BaseModel):
    audience: str | None = Field(
        None, description='Audience is the target audience for the exchanged token'
    )
    client_id: str | None = Field(
        None, description='ClientID is the OAuth 2.0 client identifier'
    )
    client_secret: str | None = Field(
        None, description='ClientSecret is the OAuth 2.0 client secret'
    )
    external_token_header_name: str | None = Field(
        None,
        description='ExternalTokenHeaderName is the name of the custom header to use when HeaderStrategy is "custom"',
    )
    header_strategy: str | None = Field(
        None,
        description='HeaderStrategy determines how to inject the token\nValid values: HeaderStrategyReplace (default), HeaderStrategyCustom',
    )
    scopes: list[str] | None = Field(
        None,
        description='Scopes is the list of scopes to request for the exchanged token',
    )
    subject_token_type: str | None = Field(
        None,
        description='SubjectTokenType specifies the type of the subject token being exchanged.\nCommon values: tokenTypeAccessToken (default), tokenTypeIDToken, tokenTypeJWT.\nIf empty, defaults to tokenTypeAccessToken.',
    )
    token_url: str | None = Field(
        None, description='TokenURL is the OAuth 2.0 token endpoint URL'
    )
