# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2025-10-24T12:14:20+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field, RootModel


class MiddlewareConfig(BaseModel):
    parameters: Optional[dict[str, Any]] = Field(
        None,
        description='Parameters is a JSON object containing the middleware parameters.\nIt is stored as a raw message to allow flexible parameter types.',
    )
    type: Optional[str] = Field(
        None, description='Type is a string representing the middleware type.'
    )
