# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-10T00:38:13+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class MiddlewareConfig(BaseModel):
    parameters: dict[str, Any] | None = Field(
        None,
        description='Parameters is a JSON object containing the middleware parameters.\nIt is stored as a raw message to allow flexible parameter types.',
    )
    type: str | None = Field(
        None, description='Type is a string representing the middleware type.'
    )
