# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-29T00:44:40+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class MiddlewareConfig(BaseModel):
    parameters: dict[str, Any] | None = Field(
        None,
        description='Parameters is a JSON object containing the middleware parameters.\nIt is stored as a raw message to allow flexible parameter types.',
    )
    type: str | None = Field(
        None, description='Type is a string representing the middleware type.'
    )


class ProxyMode(StrEnum):
    proxy_mode_sse = 'sse'
    proxy_mode_streamable_http = 'streamable-http'


class TransportType(StrEnum):
    transport_type_stdio = 'stdio'
    transport_type_sse = 'sse'
    transport_type_streamable_http = 'streamable-http'
    transport_type_inspector = 'inspector'
