# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-02-08T00:58:38+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Config(BaseModel):
    custom_header_name: str | None = Field(
        None,
        description='CustomHeaderName is the header name when HeaderStrategy is "custom".',
    )
    header_strategy: str | None = Field(
        None,
        description='HeaderStrategy determines how to inject the token: "replace" (default) or "custom".',
    )
