# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/api/openapi.json
#   timestamp: 2026-01-20T00:38:17+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field

from . import client, core
from . import groups as groups_1
from . import permissions
from . import registry as registry_1
from . import runtime
from . import secrets as secrets_1


class RegistryType(StrEnum):
    registry_type_file = 'file'
    registry_type_url = 'url'
    registry_type_api = 'api'
    registry_type_default = 'default'


class UpdateRegistryRequest(BaseModel):
    allow_private_ip: bool | None = Field(
        None, description='Allow private IP addresses for registry URL or API URL'
    )
    api_url: str | None = Field(None, description='MCP Registry API URL')
    local_path: str | None = Field(None, description='Local registry file path')
    url: str | None = Field(None, description='Registry URL (for remote registries)')


class UpdateRegistryResponse(BaseModel):
    message: str | None = Field(None, description='Status message')
    type: str | None = Field(None, description='Registry type after update')


class BulkClientRequest(BaseModel):
    groups: list[str] | None = Field(
        None, description='Groups is the list of groups configured on the client.'
    )
    names: list[client.MCPClient] | None = Field(
        None, description='Names is the list of client names to operate on.'
    )


class BulkOperationRequest(BaseModel):
    group: str | None = Field(
        None, description='Group name to operate on (mutually exclusive with names)'
    )
    names: list[str] | None = Field(
        None, description='Names of the workloads to operate on'
    )


class ClientStatusResponse(BaseModel):
    clients: list[client.MCPClientStatus] | None = None


class CreateClientRequest(BaseModel):
    groups: list[str] | None = Field(
        None, description='Groups is the list of groups configured on the client.'
    )
    name: client.MCPClient | None = None


class CreateClientResponse(BaseModel):
    groups: list[str] | None = Field(
        None, description='Groups is the list of groups configured on the client.'
    )
    name: client.MCPClient | None = None


class CreateGroupRequest(BaseModel):
    name: str | None = Field(None, description='Name of the group to create')


class CreateGroupResponse(BaseModel):
    name: str | None = Field(None, description='Name of the created group')


class CreateSecretRequest(BaseModel):
    key: str | None = Field(None, description='Secret key name')
    value: str | None = Field(None, description='Secret value')


class CreateSecretResponse(BaseModel):
    key: str | None = Field(None, description='Secret key that was created')
    message: str | None = Field(None, description='Success message')


class CreateWorkloadResponse(BaseModel):
    name: str | None = Field(None, description='Name of the created workload')
    port: int | None = Field(None, description='Port the workload is listening on')


class GroupListResponse(BaseModel):
    groups: list[groups_1.Group] | None = Field(None, description='List of groups')


class OidcOptions(BaseModel):
    audience: str | None = Field(None, description='Expected audience')
    client_id: str | None = Field(None, description='OAuth2 client ID')
    client_secret: str | None = Field(None, description='OAuth2 client secret')
    introspection_url: str | None = Field(
        None, description='Token introspection URL for OIDC'
    )
    issuer: str | None = Field(None, description='OIDC issuer URL')
    jwks_url: str | None = Field(None, description='JWKS URL for key verification')
    scopes: list[str] | None = Field(
        None, description='OAuth scopes to advertise in well-known endpoint (RFC 9728)'
    )


class ProviderCapabilitiesResponse(BaseModel):
    can_cleanup: bool | None = Field(
        None, description='Whether the provider can cleanup all secrets'
    )
    can_delete: bool | None = Field(
        None, description='Whether the provider can delete secrets'
    )
    can_list: bool | None = Field(
        None, description='Whether the provider can list secrets'
    )
    can_read: bool | None = Field(
        None, description='Whether the provider can read secrets'
    )
    can_write: bool | None = Field(
        None, description='Whether the provider can write secrets'
    )


class RegistryInfo(BaseModel):
    last_updated: str | None = Field(None, description='Last updated timestamp')
    name: str | None = Field(None, description='Name of the registry')
    server_count: int | None = Field(
        None, description='Number of servers in the registry'
    )
    source: str | None = Field(
        None,
        description='Source of the registry (URL, file path, or empty string for built-in)',
    )
    type: RegistryType | None = None
    version: str | None = Field(None, description='Version of the registry schema')


class RegistryListResponse(BaseModel):
    registries: list[RegistryInfo] | None = Field(
        None, description='List of registries'
    )


class RemoteOAuthConfig(BaseModel):
    authorize_url: str | None = Field(
        None,
        description='OAuth authorization endpoint URL (alternative to issuer for non-OIDC OAuth)',
    )
    bearer_token: secrets_1.SecretParameter | None = None
    callback_port: int | None = Field(
        None, description='Specific port for OAuth callback server'
    )
    client_id: str | None = Field(
        None, description='OAuth client ID for authentication'
    )
    client_secret: secrets_1.SecretParameter | None = None
    issuer: str | None = Field(
        None, description='OAuth/OIDC issuer URL (e.g., https://accounts.google.com)'
    )
    oauth_params: dict[str, str] | None = Field(
        None,
        description='Additional OAuth parameters for server-specific customization',
    )
    resource: str | None = Field(
        None, description='OAuth 2.0 resource indicator (RFC 8707)'
    )
    scopes: list[str] | None = Field(None, description='OAuth scopes to request')
    skip_browser: bool | None = Field(
        None,
        description='Whether to skip opening browser for OAuth flow (defaults to false)',
    )
    token_url: str | None = Field(
        None,
        description='OAuth token endpoint URL (alternative to issuer for non-OIDC OAuth)',
    )
    use_pkce: bool | None = Field(
        None, description='Whether to use PKCE for the OAuth flow'
    )


class SecretKeyResponse(BaseModel):
    description: str | None = Field(
        None, description='Optional description of the secret'
    )
    key: str | None = Field(None, description='Secret key name')


class SetupSecretsRequest(BaseModel):
    password: str | None = Field(
        None,
        description='Password for encrypted provider (optional, can be set via environment variable)\nTODO Review environment variable for this',
    )
    provider_type: str | None = Field(
        None, description='Type of the secrets provider (encrypted, 1password, none)'
    )


class SetupSecretsResponse(BaseModel):
    message: str | None = Field(None, description='Success message')
    provider_type: str | None = Field(
        None, description='Type of the secrets provider that was setup'
    )


class ToolOverride(BaseModel):
    description: str | None = Field(None, description='Description of the tool')
    name: str | None = Field(None, description='Name of the tool')


class UpdateSecretRequest(BaseModel):
    value: str | None = Field(None, description='New secret value')


class UpdateSecretResponse(BaseModel):
    key: str | None = Field(None, description='Secret key that was updated')
    message: str | None = Field(None, description='Success message')


class VersionResponse(BaseModel):
    version: str | None = None


class WorkloadStatusResponse(BaseModel):
    status: runtime.WorkloadStatus | None = None


class CreateRequest(BaseModel):
    authz_config: str | None = Field(None, description='Authorization configuration')
    cmd_arguments: list[str] | None = Field(
        None, description='Command arguments to pass to the container'
    )
    env_vars: dict[str, str] | None = Field(
        None, description='Environment variables to set in the container'
    )
    group: str | None = Field(None, description='Group name this workload belongs to')
    headers: list[registry_1.Header] | None = None
    host: str | None = Field(None, description='Host to bind to')
    image: str | None = Field(None, description='Docker image to use')
    name: str | None = Field(None, description='Name of the workload')
    network_isolation: bool | None = Field(
        None,
        description='Whether network isolation is turned on. This applies the rules in the permission profile.',
    )
    oauth_config: RemoteOAuthConfig | None = None
    oidc: OidcOptions | None = None
    permission_profile: permissions.Profile | None = None
    proxy_mode: str | None = Field(None, description='Proxy mode to use')
    proxy_port: int | None = Field(
        None, description='Port for the HTTP proxy to listen on'
    )
    secrets: list[secrets_1.SecretParameter] | None = Field(
        None, description='Secret parameters to inject'
    )
    target_port: int | None = Field(
        None, description='Port to expose from the container'
    )
    tools: list[str] | None = Field(None, description='Tools filter')
    tools_override: dict[str, ToolOverride] | None = Field(
        None, description='Tools override'
    )
    transport: str | None = Field(None, description='Transport configuration')
    trust_proxy_headers: bool | None = Field(
        None, description='Whether to trust X-Forwarded-* headers from reverse proxies'
    )
    url: str | None = Field(None, description='Remote server specific fields')
    volumes: list[str] | None = Field(None, description='Volume mounts')


class GetSecretsProviderResponse(BaseModel):
    capabilities: ProviderCapabilitiesResponse | None = None
    name: str | None = Field(None, description='Name of the secrets provider')
    provider_type: str | None = Field(None, description='Type of the secrets provider')


class ListSecretsResponse(BaseModel):
    keys: list[SecretKeyResponse] | None = Field(
        None, description='List of secret keys'
    )


class UpdateRequest(BaseModel):
    authz_config: str | None = Field(None, description='Authorization configuration')
    cmd_arguments: list[str] | None = Field(
        None, description='Command arguments to pass to the container'
    )
    env_vars: dict[str, str] | None = Field(
        None, description='Environment variables to set in the container'
    )
    group: str | None = Field(None, description='Group name this workload belongs to')
    headers: list[registry_1.Header] | None = None
    host: str | None = Field(None, description='Host to bind to')
    image: str | None = Field(None, description='Docker image to use')
    network_isolation: bool | None = Field(
        None,
        description='Whether network isolation is turned on. This applies the rules in the permission profile.',
    )
    oauth_config: RemoteOAuthConfig | None = None
    oidc: OidcOptions | None = None
    permission_profile: permissions.Profile | None = None
    proxy_mode: str | None = Field(None, description='Proxy mode to use')
    proxy_port: int | None = Field(
        None, description='Port for the HTTP proxy to listen on'
    )
    secrets: list[secrets_1.SecretParameter] | None = Field(
        None, description='Secret parameters to inject'
    )
    target_port: int | None = Field(
        None, description='Port to expose from the container'
    )
    tools: list[str] | None = Field(None, description='Tools filter')
    tools_override: dict[str, ToolOverride] | None = Field(
        None, description='Tools override'
    )
    transport: str | None = Field(None, description='Transport configuration')
    trust_proxy_headers: bool | None = Field(
        None, description='Whether to trust X-Forwarded-* headers from reverse proxies'
    )
    url: str | None = Field(None, description='Remote server specific fields')
    volumes: list[str] | None = Field(None, description='Volume mounts')


class WorkloadListResponse(BaseModel):
    workloads: list[core.Workload] | None = Field(
        None, description='List of container information for each workload'
    )


class GetServerResponse(BaseModel):
    is_remote: bool | None = Field(
        None, description='Indicates if this is a remote server'
    )
    remote_server: registry_1.RemoteServerMetadata | None = None
    server: registry_1.ImageMetadata | None = None


class ListServersResponse(BaseModel):
    remote_servers: list[registry_1.RemoteServerMetadata] | None = Field(
        None, description='List of remote servers in the registry (if any)'
    )
    servers: list[registry_1.ImageMetadata] | None = Field(
        None, description='List of container servers in the registry'
    )


class GetRegistryResponse(BaseModel):
    last_updated: str | None = Field(None, description='Last updated timestamp')
    name: str | None = Field(None, description='Name of the registry')
    registry: registry_1.Registry | None = None
    server_count: int | None = Field(
        None, description='Number of servers in the registry'
    )
    source: str | None = Field(
        None,
        description='Source of the registry (URL, file path, or empty string for built-in)',
    )
    type: RegistryType | None = None
    version: str | None = Field(None, description='Version of the registry schema')
