name: Main build for Helm Charts

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - helm/**

jobs:
  publish-charts:
    name: Publish Helm Charts
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/releaser-helm-charts.yml

