# These workflows run on every push to the main branch
name: Main Branch Checks
permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  code_checks:
    name: Code Checks
    uses: ./.github/workflows/code-checks.yml
